version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - db
    command: >
      bash -c "mix ecto.create &&
      mix ecto.migrate &&
      mix phx.server"
  
    
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  