version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - db
    command: >
      bash -c "
      mix deps.get && mix deps.compile &&
      mix ecto.create && mix ecto.migrate &&
      mix phx.server"
  
    
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  